- name: "Check PostgreSQL instance(s)"
  ansible.builtin.stat:
    path: "{{ pg_systemd_service_dir }}/postgresql-{{ pg_version }}-{{ pg_instance }}.service"
  register: service_status

- name: "Stop PostgreSQL instance(s)"
  ansible.builtin.systemd:
    name: "postgresql-{{ pg_version }}-{{ pg_instance }}"
    enabled: no
    state: stopped
  when: service_status.stat.exists
